yolo_model:

  config_file:
    name: yolov3-tiny-custom.cfg
  weight_file:
    name: yolov3-tiny-custom_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - emergency
      - normal
