set(_CATKIN_CURRENT_PACKAGE "keyboard_teleop")
set(keyboard_teleop_VERSION "0.0.0")
set(keyboard_teleop_MAINTAINER "wecar <wecar@todo.todo>")
set(keyboard_teleop_PACKAGE_FORMAT "2")
set(keyboard_teleop_BUILD_DEPENDS "roscpp" "std_msgs")
set(keyboard_teleop_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(keyboard_teleop_BUILDTOOL_DEPENDS "catkin")
set(keyboard_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(keyboard_teleop_EXEC_DEPENDS "roscpp" "std_msgs")
set(keyboard_teleop_RUN_DEPENDS "roscpp" "std_msgs")
set(keyboard_teleop_TEST_DEPENDS )
set(keyboard_teleop_DOC_DEPENDS )
set(keyboard_teleop_URL_WEBSITE "")
set(keyboard_teleop_URL_BUGTRACKER "")
set(keyboard_teleop_URL_REPOSITORY "")
set(keyboard_teleop_DEPRECATED "")